version: '3.3'

services: 
  db:
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    volumes: 
      - db-test:/var/lib/mysql

volumes: 
  db-test: